### ISSUE TITLE
Minifier doesn't minify JavaScript

### ISSUE THREAD

**Issue by base698** [CodingCarter/minifier#7]
### Sample program:
```
import { Language,minify } from "https://deno.land/x/minifier/mod.ts";

var code = {
            "file.js": `function add(first, second) {
                    // some comment
                    return first + second;
            }`,
            "file.css": ".arule { color: red; font-weight: 10; }"
};

var result = minify(Language.JS, code["file.js"]);

console.log(result);
```

### Results
```
function add(first, second) { // some comment return first + second; }
```

### Expected
```
function add(a,b){return a + b;}
```

**Comment by sno2** [comment]
Already got this down in #1.  I can't get the WASM to build correctly on Windows with MingW even after spending 3 days on it.  Currently, waiting for the Deno refactor in v1.10 (supposed to come out in two weeks) in which Deno will help handle the WASM encoding op (handshaking between WASM and JS types) to try to fix this again.
